spring:
  application:
    name:mimigate

  cloud:
    gateway:
      routes:
        - id: rental
          uri : http://127.0.0.1:5678
          predicates:
            - Path=/rental/**
##          filters:
        - id: users
          uri : http://127.0.0.1:5679
          predicates:
            - Path=/users/**
##          filters:
        - id: equipment
          uri : http://127.0.0.1:5680
          predicates:
            - Path=/equipment/**
##          filters:

        - id: fr
          uri : http://127.0.0.1:5675
          predicates:
            - Path=/frt/**
server:
  port: 5676

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:5677/eureka

